### ISSUE TITLE
GOARCH=js ???

### ISSUE THREAD

**Issue by ghost** [shurcooL/resume#3]
SO does this work with golang 7.1 and gopherjs ?

GOARCH=js go build
cmd/go: unsupported GOOS/GOARCH pair darwin/js
x-MacBook-Pro:frontend apple$ GOARCH=js GOOS=darwin go build
cmd/go: unsupported GOOS/GOARCH pair darwin/js

**Comment by shurcooL** [comment]
Go 1.7.1 does not support compiling for js architcture.

There is an unfinished PR in GopherJS repo to make a fork of `go` build tool that does.

**Comment by gedw99** [comment]
I saw it.
I guess version 1.8 then ??

**Comment by shurcooL** [comment]
I don't have a specific estimate for when it'll be finished.
